### ISSUE TITLE
Custom Disc Placement Causes Overlapping in 4:3

### ISSUE THREAD

**Issue by meow5219** [NinjaCheetah/wii-menu-visual-patcher#1]
![image](https://github.com/NinjaCheetah/wii-menu-visual-patcher/assets/79637866/bd7273e7-7448-4747-84c8-770a2f6ccc0e)
(old screenshot)
as the title says

**Comment by NinjaCheetah** [comment]
Hmm okay. I hadn't really thought about how 4:3 would look when the images are re-positioned since I always use 16:9, and I knew that it was at least acceptable with the default placements. I'll take a look at it and see if I can adjust the placements so that it works in both 4:3 and 16:9.

**Comment by NinjaCheetah** [comment]
I have a resolution, thanks to the Korean Disc Channel already having the offsets I need built in! Working on making the script use those offsets instead of the ones I made, which will fix this issue.

**Comment by NinjaCheetah** [comment]
All fixed now! Enjoy!
